name: Java CI with Maven and Selenium

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '*/2 * * * *' # Запуск каждые 2 минуты (если нужно)

jobs:
  build:
    runs-on: ubuntu-latest # Это Linux-сервер GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with Maven
        # Для Linux в GitHub Actions браузер ОБЯЗАТЕЛЬНО должен быть в headless режиме
        run: mvn -B test
